export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT'

export const PRODUCT_GET = 'PRODUCT_GET'
export const PRODUCT_ADD = 'PRODUCT_ADD'
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE'
export const PRODUCT_REMOVE = 'PRODUCT_REMOVE'
export const PRODUCT_LOADER = 'PRODUCT_LOADER'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'

export const ADD_TO_CART = 'ADD_TO_CART'
export const QTY_INCREMENT = 'QTY_INCREMENT'
export const QTY_DECREMENT = 'QTY_DECREMENT'
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE'