export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT'

export const PRODUCT_GET = 'PRODUCT_GET'
export const PRODUCT_ADD = 'PRODUCT_ADD'
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE'
export const PRODUCT_REMOVE = 'PRODUCT_REMOVE'


